version : '3.7'

services:

  db:
    container_name: mysql-db
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_USER=area_user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=area_db
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - 3308:3306
    tty: true
